# Generated by Django 2.2.18 on 2021-02-18 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210215_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='Post',
        ),
    ]
